export const simConnectDataTypeDefault = {
    PLANE_TITLE: '',
    SIMULATION_RATE: 1,
    SIMULATION_RATE_VALID: 1,
    SIMULATION_RATE_INVALID_REASON: '',
    TRANSPONDER_CODE: '0000',
    ADF1_ACTIVE_FREQUENCY: '0000',
    ADF1_STANDBY_FREQUENCY: '0000',
    COM1_ACTIVE_FREQUENCY: 118,
    COM2_ACTIVE_FREQUENCY: 118,
    COM1_STANDBY_FREQUENCY: 118,
    COM2_STANDBY_FREQUENCY: 118,
    NAV1_ACTIVE_FREQUENCY: 108,
    NAV2_ACTIVE_FREQUENCY: 108,
    NAV1_STANDBY_FREQUENCY: 108,
    NAV2_STANDBY_FREQUENCY: 108,
    KOHLSMAN_SETTING_HG: 29.92
}